POST http://localhost:8080/events
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImRlZXBhbnNodUBnbWFpbC5jb20iLCJleHAiOjE3MzIyNTY5MzMsInVzZXJJZCI6MX0.dkIadN9CG6gOyvUhDXvMcTOwlmG6-B9i9zpMud_czlw

{
    "name" : "Test Match event",
    "description":"A Best test match that you will ever witnesed",
    "location" : "Oconoa, Australia",
    "dateTime" : "2024-01-02T15:04:05Z"
}