POST http://localhost:8080/events
Content-Type: application/json

{
    "name" : "Test Match event",
    "description":"A Best test match that you will ever witnesed",
    "location" : "Oconoa, Australia",
    "dateTime" : "2024-01-02T15:04:05Z"
}