POST http://localhost:8080/events/1/register
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImRlZXBhbnNodUBnbWFpbC5jb20iLCJleHAiOjE3MzIyNTk5MDcsInVzZXJJZCI6MX0.e1glBavQTfyZvl0v8AuI1l8mR3fjVWBGIsbPFGOSVNc